### ISSUE TITLE
Clarify in readme that `ignoreAction` for GA Workflows is about steps

### ISSUE THREAD

**Issue by WyriHaximus** [WyriHaximus/github-action-wait-for-status#35]
It's the name of the step, in your case `Automerge Dependabot` I guess? Should clarify that 🤐

_Originally posted by @WyriHaximus in https://github.com/WyriHaximus/github-action-wait-for-status/issues/34#issuecomment-703516435_

Is about this part of the documentation: https://github.com/WyriHaximus/github-action-wait-for-status#ignoreactions

**Comment by boldandbusted** [comment]
So, the example in the README.md (on main) is confusing for me, because, if I'm reading it correctly, the `ignoreAction: automerge` set there apparently doesn't match any `step:` `- name:` value in the same example. And does this mean you must add 'name:' to each step for this Action to 'see' it? Maybe this is OT for this Issue, but is it possible that this field (or a new field) could match on a job name, too? Thanks for this project!
