### ISSUE TITLE
"skipped" marked as failure

### ISSUE THREAD

**Issue by RebeccaStevens** [WyriHaximus/github-action-wait-for-status#41]
If a job is skipped it is marked as a failure. This seems like a bug to me.

```sh
wait.DEBUG: Check "Job Name" has the following status "completed" and conclusion "skipped"
wait.DEBUG: Check (Job Name) failed, marking resolve and failure

wait.INFO: Final status: failure
```

**Comment by WyriHaximus** [comment]
Hah good point, I agree. Skipped jobs should be marked as successful and not as a failure :+1:

**Comment by WyriHaximus** [comment]
I'll do some other changes tonight before release v1.3 with this fix :+1:

**Comment by WyriHaximus** [comment]
@RebeccaStevens Thanks again for putting the same into this. Just release [`v1.3(.0)`](https://github.com/WyriHaximus/github-action-wait-for-status/releases/tag/v1.3.0) with this fix. Interestingly enough I got caught by this bug when trying to release 1.3 last night due to a fluxe in GitHub's UI accidentally closing the milestone twice :joy:
